# Generated by Django 2.1.2 on 2019-04-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('predictor', models.FileField(upload_to='predictor')),
                ('dataset', models.FileField(upload_to='dataset')),
            ],
        ),
    ]
